MAX9814
Provides the core capabilities for microphone MAX9814 related functions.
Enumerations
enum MAX9814_GainValueType { MAX9814_VCC_GAIN = 40
, MAX9814_GND_GAIN = 50
, MAX9814_FLOAT_GAIN = 60
 }
Enumeration for selecting the analog gain of the MAX9814 microphone module.
Functions
void MAX9814_Init (MAX9814_GainValueType mic_gain)
Initializes the MAX9814 microphone module.
float MAX9814_Read (void)
Reads the current ambient sound level in decibels (dB SPL approximation).
void MAX9814_SetGain (MAX9814_GainValueType mic_gain)
Updates the analog gain setting of the MAX9814 microphone module.
Detailed Description
Provides the core capabilities for microphone MAX9814 related functions.
Enumeration Type Documentation
MAX9814_GainValueType
enum MAX9814_GainValueType
Enumeration for selecting the analog gain of the MAX9814 microphone module.
   This enum defines the gain levels that can be applied to the MAX9814 by
   configuring its gain selection pin. Each level corresponds to a specific
   hardware wiring: VCC, GND, or floating input.
Enumerator
MAX9814_VCC_GAIN Gain = 40 dB (Gain pin connected to VCC)
MAX9814_GND_GAIN Gain = 50 dB (Gain pin connected to GND)
MAX9814_FLOAT_GAIN Gain = 60 dB (Gain pin left floating/open)
Definition at line 37 of file max9814.h.
Function Documentation
MAX9814_Init()
void MAX9814_Init (MAX9814_GainValueType mic_gain)
Initializes the MAX9814 microphone module.
   This function sets up the ADC input channel, configures the gain selection pin,
   and performs offset calibration for the ADC to ensure accurate signal centering.
   It must be called before any sound level measurements are taken.
Parameters
mic_gain Initial gain level for the MAX9814 microphone. Acceptable values:
MAX9814_VCC_GAIN (40 dB)
MAX9814_GND_GAIN (50 dB)
MAX9814_FLOAT_GAIN (60 dB)
Note
Requires that ADC and GPIO configuration functions are properly implemented.
Definition at line 79 of file max9814.c.
References ADC_Init(), MAX9814_SetGain(), and PINCFG_Function().
Referenced by MICROPHONE_Init().
MAX9814_Read()
float MAX9814_Read (void)
Reads the current ambient sound level in decibels (dB SPL approximation).
   This function captures multiple ADC samples, calculates the RMS (Root Mean Square)
   value of the signal, and converts it to decibels. The calculation also includes
   internal compensation for the configured analog gain.

   It also performs automatic gain control (AGC) by adjusting the hardware gain
   based on configurable dB thresholds with hysteresis.
Returns
Sound pressure level in decibels (dB SPL approximation).
Return values
-INFINITY If the signal level is too low to compute a valid dB value.
>0 Valid sound level in dB.
Definition at line 86 of file max9814.c.
References ADC_Read().
Referenced by MICROPHONE_Read().
MAX9814_SetGain()
void MAX9814_SetGain (MAX9814_GainValueType mic_gain)
Updates the analog gain setting of the MAX9814 microphone module.
  This function sets the appropriate logic level on the GAIN pin to configure
  the microphone's analog gain (40 dB, 50 dB, or 60 dB). It also updates the
  internal compensation factor for dB conversion and recalculates the reference
  output voltage based on the selected gain.
Parameters
mic_gain New gain level to apply. Options:
MAX9814_VCC_GAIN (40 dB)
MAX9814_GND_GAIN (50 dB)
MAX9814_FLOAT_GAIN (60 dB)
Definition at line 95 of file max9814.c.
References MAX9814_FLOAT_GAIN, MAX9814_GND_GAIN, MAX9814_VCC_GAIN, PIN_Clear(), PIN_Direction(), and PIN_Set().
Referenced by MAX9814_Init(), and MICROPHONE_SetGain().