NTP
Provides the core capabilities for NTP related functions.
Data Structures
struct NTP_Packet
Represents a 48-byte NTP (Network Time Protocol) packet structure.
Enumerations
enum NTP_StateValueType { NTP_IDLE
, NTP_PROCESSING
, NTP_READY
 }
Internal state of the NTP client.
Functions
void NTP_Init (void)
Initializes the NTP module and creates the background task.
bool NTP_Ready (void)
Checks if the NTP module has been initialised.
NTP_StateValueType NTP_GetState (void)
Retrieves the current state of the NTP client.
void NTP_RequestTime (void)
Sends a time request to the configured NTP server.
bool NTP_GetTimestamp (time_t *timestamp)
Retrieves the latest timestamp received from the NTP server.
bool NTP_RequestAndWait (time_t *timestamp)
Sends an NTP request and blocks until a response is received.
Detailed Description
Provides the core capabilities for NTP related functions.
Enumeration Type Documentation
NTP_StateValueType
enum NTP_StateValueType
Internal state of the NTP client.
Enumerator
NTP_IDLE NTP client is idle or ready for a new request
NTP_PROCESSING NTP client is processing a time request
NTP_READY NTP client has received a valid timestamp
Definition at line 88 of file ntp.h.
Function Documentation
NTP_GetState()
NTP_StateValueType NTP_GetState (void)
Retrieves the current state of the NTP client.
   Returns the internally tracked NTP client state, ensuring thread safety
   by using a FreeRTOS mutex.
Returns
The current state as a value of NTP_StateValueType.
Return values
NTP_IDLE If the client is idle or ready for a new request.
NTP_PROCESSING If the client is processing a time request.
NTP_READY If the client has received a valid timestamp.
Definition at line 206 of file ntp.c.
References NTP_IDLE.
Referenced by NTP_RequestAndWait(), and NTP_RequestTime().
NTP_GetTimestamp()
bool NTP_GetTimestamp (time_t * timestamp)
Retrieves the latest timestamp received from the NTP server.
   This function returns the converted "struct tm" (UTC/GMT) if a valid
   timestamp is available. It resets the internal state to "NTP_IDLE"
   after a successful retrieval.
Parameters
timestamp Pointer to a "time_t" where the result will be stored.
Return values
true If a valid timestamp was available and "timestamp" was populated.
false If the timestamp is not available or "timestamp" is NULL.
Note
This function is non-blocking and should be used after calling NTP_RequestTime. Use NTP_RequestAndWait for a blocking alternative.
Definition at line 224 of file ntp.c.
References NTP_IDLE, and NTP_READY.
Referenced by NTP_RequestAndWait().
NTP_Init()
void NTP_Init (void)
Initializes the NTP module and creates the background task.
   This function sets up the mutex used to protect access to shared NTP state
   and creates the FreeRTOS task responsible for handling NTP time synchronisation.
Note
Must be called once before any other NTP-related function.
Definition at line 195 of file ntp.c.
Referenced by WIFI_Init().
NTP_Ready()
bool NTP_Ready (void)
Checks if the NTP module has been initialised.
   This function verifies whether the NTP background task has been successfully created,
   indicating that the NTP module is ready to process time requests.
Return values
true If the NTP task has been created and the module is ready.
false If the NTP task has not been created (NTP_Init was not called or failed).
Definition at line 202 of file ntp.c.
NTP_RequestAndWait()
bool NTP_RequestAndWait (time_t * timestamp)
Sends an NTP request and blocks until a response is received.
   This function combines the request and polling logic to retrieve
   the timestamp in a blocking manner, useful in cases where the application
   flow depends on synchronized time.
Parameters
timestamp Pointer to a "time_t" where the result will be stored.
Return values
true If the timestamp was received and "timestamp" was successfully populated.
false If an error or if "timestamp" is NULL.
Definition at line 243 of file ntp.c.
References NTP_GetState(), NTP_GetTimestamp(), NTP_IDLE, and NTP_RequestTime().
NTP_RequestTime()
void NTP_RequestTime (void)
Sends a time request to the configured NTP server.
   This function notifies the NTP task to start the process of connecting,
   sending the NTP packet, and waiting for a valid response.
Note
This function is non-blocking needs a follow up call of NTP_GetTime. Use NTP_RequestAndWait to block until time is available.
Definition at line 217 of file ntp.c.
References NTP_GetState(), NTP_IDLE, and NTP_PROCESSING.
Referenced by NTP_RequestAndWait().