FLASH
Provides the core capabilities for flash functions.
Enumerations
enum FLASH_StatusCodeType {
CMD_SUCCESS
, INVALID_COMMAND
, SRC_ADDR_ERROR
, DST_ADDR_ERROR
,
SRC_ADDR_NOT_MAPPED
, DST_ADDR_NOT_MAPPED
, COUNT_ERROR
, INVALID_SECTOR
,
SECTOR_NOT_BLANK
, SECTOR_NOT_PREPARED_FOR_WRITE_OPERATION
, COMPARE_ERROR
, BUSY
 }
Return status codes from IAP Flash operations.
enum FLASH_CommandCodeType {
Prepare_Sectors_For_Write = 50
, COPY_RAM_TO_FLASH = 51
, Erase_Sectors = 52
, Blank_Check_Sectors = 53
,
Read_Part_Identification_Number = 54
, Read_Boot_Code_Version_Number = 55
, Compare_Addr1_Addr2_nBytes = 56
, Re_Invoke_ISP = 57
,
Read_Device_Serial_Number = 58
 }
IAP command codes for Flash operations.
Functions
unsigned int FLASH_EraseSector (unsigned int sector)
Erases a given Flash sector.
unsigned int FLASH_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Writes data from RAM to a given Flash address.
unsigned int FLASH_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Compares memory contents between Flash and RAM.
Detailed Description
Provides the core capabilities for flash functions.
Enumeration Type Documentation
FLASH_CommandCodeType
enum FLASH_CommandCodeType
IAP command codes for Flash operations.
Enumerator
Prepare_Sectors_For_Write Prepare sectors for write/erase
COPY_RAM_TO_FLASH Copy data from RAM to Flash
Erase_Sectors Erase Flash sectors
Blank_Check_Sectors Check if sectors are blank
Read_Part_Identification_Number Read part ID number
Read_Boot_Code_Version_Number Read boot code version
Compare_Addr1_Addr2_nBytes Compare memory contents
Re_Invoke_ISP Reinvoke ISP mode
Read_Device_Serial_Number Read device serial number
Definition at line 51 of file flash.h.
FLASH_StatusCodeType
enum FLASH_StatusCodeType
Return status codes from IAP Flash operations.
Enumerator
CMD_SUCCESS Operation successful
INVALID_COMMAND Invalid IAP command code
SRC_ADDR_ERROR Source address error (not on word boundary)
DST_ADDR_ERROR Destination address error (not on word boundary)
SRC_ADDR_NOT_MAPPED Source address not mapped in memory
DST_ADDR_NOT_MAPPED Destination address not mapped in memory
COUNT_ERROR Byte count is not valid
INVALID_SECTOR Sector number is invalid or out of range
SECTOR_NOT_BLANK Sector is not blank
SECTOR_NOT_PREPARED_FOR_WRITE_OPERATION Sector not prepared before writing
COMPARE_ERROR Compare operation failed (data mismatch)
BUSY Flash is busy with another operation
Definition at line 32 of file flash.h.
Function Documentation
FLASH_EraseSector()
unsigned int FLASH_EraseSector (unsigned int sector)
Erases a given Flash sector.
Parameters
sector Sector number to erase (e.g., 0 to 29 for LPC1769)
Returns
Status code indicating success or specific error.
Definition at line 34 of file flash.c.
References CMD_SUCCESS, Erase_Sectors, and Prepare_Sectors_For_Write.
Referenced by FLASHCONTROL_EraseSector().
FLASH_VerifyData()
unsigned int FLASH_VerifyData (void * dstAddr, void * srcAddr, unsigned int size)
Compares memory contents between Flash and RAM.
Parameters
dstAddr Destination address (typically Flash)
srcAddr Source address (typically RAM)
size Number of bytes to compare
Returns
CMD_SUCCESS if equal, COMPARE_ERROR if data differs
Definition at line 85 of file flash.c.
References Compare_Addr1_Addr2_nBytes.
Referenced by FLASHCONTROL_VerifyData().
FLASH_WriteData()
unsigned int FLASH_WriteData (void * dstAddr, void * srcAddr, unsigned int size)
Writes data from RAM to a given Flash address.
Parameters
dstAddr Destination Flash address (must be 256-byte aligned)
srcAddr Source RAM address (must be word-aligned)
size Number of bytes to write (must be multiple of 256)
Returns
Status code indicating success or specific error.
Definition at line 58 of file flash.c.
References CMD_SUCCESS, COPY_RAM_TO_FLASH, INVALID_SECTOR, and Prepare_Sectors_For_Write.
Referenced by FLASHCONTROL_WriteData().