FLASH_FreeRTOS
Provides the core capabilities for flash memory FreeRTOS functions.
Macros
#define FLASH_RTOS_ERROR -1
Error code returned by FLASH_RTOS functions when an error occurs.
Functions
void FLASH_RTOS_Init (void)
Initializes the internal mutex used to protect flash operations.
int FLASH_RTOS_EraseSector (unsigned int sector)
Erases the specified flash sector in a thread-safe manner.
int FLASH_RTOS_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Writes data to flash memory in a thread-safe manner.
int FLASH_RTOS_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Verifies flash memory content against a RAM buffer in a thread-safe manner.
Detailed Description
Provides the core capabilities for flash memory FreeRTOS functions.
Function Documentation
FLASH_RTOS_EraseSector()
int FLASH_RTOS_EraseSector (unsigned int sector)
Erases the specified flash sector in a thread-safe manner.
Parameters
sector The sector number to erase.
Returns
int Result code from FLASHCONTROL_EraseSector or FLASH_RTOS_ERROR if mutex is unavailable.
Definition at line 29 of file flash_rtos.c.
References FLASH_RTOS_ERROR, and FLASHCONTROL_EraseSector().
FLASH_RTOS_Init()
void FLASH_RTOS_Init (void)
Initializes the internal mutex used to protect flash operations.
This function must be called before any other FLASH_RTOS function is used.
Definition at line 23 of file flash_rtos.c.
FLASH_RTOS_VerifyData()
int FLASH_RTOS_VerifyData (void * dstAddr, void * srcAddr, unsigned int size)
Verifies flash memory content against a RAM buffer in a thread-safe manner.
Parameters
dstAddr Address in flash memory to verify.
srcAddr Address in RAM to compare with.
size Number of bytes to verify (up to 4096).
Returns
int Result code from FLASHCONTROL_VerifyData or FLASH_RTOS_ERROR if mutex is unavailable.
Definition at line 55 of file flash_rtos.c.
References FLASH_RTOS_ERROR, and FLASHCONTROL_VerifyData().
FLASH_RTOS_WriteData()
int FLASH_RTOS_WriteData (void * dstAddr, void * srcAddr, unsigned int size)
Writes data to flash memory in a thread-safe manner.
Parameters
dstAddr Destination address in flash memory.
srcAddr Source address in RAM.
size Number of bytes to write (up to 4096).
Returns
int Result code from FLASHCONTROL_WriteData or FLASH_RTOS_ERROR if mutex is unavailable.
Definition at line 42 of file flash_rtos.c.
References FLASH_RTOS_ERROR, and FLASHCONTROL_WriteData().