BUZZER
Provides the core capabilities for buzzer handling functions.
Functions
void BUZZER_Init (void)
Initializes the buzzer as a GPIO output.
void BUZZER_On (void)
Turns the buzzer On.
void BUZZER_Off (void)
Turns the buzzer Off.
void BUZZER_Alarm (uint32_t time)
Turns the buzzer on for a specified duration.
Detailed Description
Provides the core capabilities for buzzer handling functions.
Function Documentation
BUZZER_Alarm()
void BUZZER_Alarm (uint32_t time)
Turns the buzzer on for a specified duration.
Parameters
time Represents the duration in milliseconds.
Definition at line 33 of file buzzer.c.
References BUZZER_Off(), BUZZER_On(), and DELAY_Stopwatch().