PIN
Provides the core capabilities for pin related functions.
Enumerations
enum PIN_ValueEnum
Pin name enumeration.
enum PIN_PortEnum
Port name enumeration.
enum PIN_DirectionEnum
Pin direction enumeration.
Functions
void PIN_Direction (PIN_ValueType pinId, PIN_DIRType dir)
Configures the direction of the specified pin.
void PIN_Set (PIN_ValueType pinId)
Sets the specified pin to logical HIGH.
void PIN_Clear (PIN_ValueType pinId)
Clears the specified pin to logical LOW.
uint32_t PIN_Value (PIN_ValueType pinId)
Reads the current logical state of the specified pin.
void PIN_PortWrite (PIN_PortType portId, uint32_t value, uint32_t mask)
Writes a masked value to the entire GPIO port.
Detailed Description
Provides the core capabilities for pin related functions.
Function Documentation
PIN_Clear()
void PIN_Clear (PIN_ValueType pinId)
Clears the specified pin to logical LOW.
Parameters
pinId The identifier of the pin to clear.
Definition at line 44 of file pin.c.
References LPC_GPIO_NUM_PINS.
Referenced by BUZZER_Off(), LED_Off(), LED_On(), and MAX9814_SetGain().
PIN_Direction()
void PIN_Direction (PIN_ValueType pinId, PIN_DIRType dir)
Configures the direction of the specified pin.
Parameters
pinId The identifier of the pin.
dir The desired direction of the pin: INPUT or OUTPUT.
Definition at line 21 of file pin.c.
References LPC_GPIO_NUM_PINS.
Referenced by BUZZER_Init(), LED_Init(), and MAX9814_SetGain().
PIN_PortWrite()
void PIN_PortWrite (PIN_PortType portId, uint32_t value, uint32_t mask)
Writes a masked value to the entire GPIO port.
      Only bits specified by the mask are affected; others remain unchanged.
Parameters
portId The identifier of the port (Port0, Port1, Port2, Port3).
value The bits to write on the port (only bits in mask apply).
mask A bitmask selecting which bits in the port are modified.
Definition at line 63 of file pin.c.
PIN_Set()
void PIN_Set (PIN_ValueType pinId)
Sets the specified pin to logical HIGH.
Parameters
pinId The identifier of the pin to set.
Definition at line 35 of file pin.c.
References LPC_GPIO_NUM_PINS.
Referenced by BUZZER_On(), LED_Off(), LED_On(), and MAX9814_SetGain().
PIN_Value()
uint32_t PIN_Value (PIN_ValueType pinId)
Reads the current logical state of the specified pin.
Parameters
pinId The identifier of the pin to read.
Returns
uint32_t The current value of the pin (non-zero if HIGH, zero if LOW).
Definition at line 53 of file pin.c.
References LPC_GPIO_NUM_PINS.
Referenced by LED_GetState().