PINCONFIG
Provides the core capabilities for pin configuration functions.
Macros
#define LPC_GPIO_NUM_PINS 32
Number of GPIO pins per port on the LPC microcontroller (32 pins).
Enumerations
enum PINCFG_FunctionEnum
Enumeration of possible functions for a pin.
enum PINCFG_ResistorModeEnum { PULL_UP
, REPEATER
, NONE
, PULL_DOWN
 }
Enumeration for internal resistor modes of the pin.
enum PINCFG_OpenDrainModeEnum { NORMAL
, OPEN_DRAIN
 }
Enumeration for the open-drain mode of the pin.
Functions
void PINCFG_Function (PIN_ValueType pinId, PINCFG_FunctionType func)
Sets the function of the specified pin (e.g., GPIO, UART, SPI, etc.)
void PINCFG_Mode (PIN_ValueType pinId, PINCFG_ResistorModeType mode)
Configures the internal resistor mode of the specified pin.
void PINCFG_OpenDrainMode (PIN_ValueType pinId, PINCFG_OpenDrainModeType mode)
Configures the open-drain mode of the specified pin.
Detailed Description
Provides the core capabilities for pin configuration functions.
Enumeration Type Documentation
PINCFG_FunctionEnum
enum PINCFG_FunctionEnum
Enumeration of possible functions for a pin.
Each pin can be configured for a specific function such as GPIO, UART, SPI, I2C, PWM, ADC, etc. The numeric value corresponds to the PINSEL register configuration.
Definition at line 41 of file pinconfig.h.
PINCFG_OpenDrainModeEnum
enum PINCFG_OpenDrainModeEnum
Enumeration for the open-drain mode of the pin.
Defines if the pin operates in normal or open-drain mode.
Enumerator
NORMAL Normal mode
OPEN_DRAIN Open-drain mode enabled
Definition at line 79 of file pinconfig.h.
PINCFG_ResistorModeEnum
enum PINCFG_ResistorModeEnum
Enumeration for internal resistor modes of the pin.
Defines the internal resistor mode: pull-up, pull-down, repeater, or none.
Enumerator
PULL_UP Internal pull-up resistor enabled
REPEATER Repeater mode
NONE No internal resistor
PULL_DOWN Internal pull-down resistor enabled
Definition at line 67 of file pinconfig.h.
Function Documentation
PINCFG_Function()
void PINCFG_Function (PIN_ValueType pinId, PINCFG_FunctionType func)
Sets the function of the specified pin (e.g., GPIO, UART, SPI, etc.)
      This function updates the appropriate bits in the PINSEL registers for the given pin.
Parameters
pinId Pin identifier
func Function to assign to the pin
Definition at line 16 of file pinconfig.c.
References LPC_GPIO_NUM_PINS.
Referenced by ADC_Init(), BUZZER_Init(), LED_Init(), and MAX9814_Init().
PINCFG_Mode()
void PINCFG_Mode (PIN_ValueType pinId, PINCFG_ResistorModeType mode)
Configures the internal resistor mode of the specified pin.
      This sets the corresponding bits in the PINMODE registers to enable pull-up, pull-down, repeater, or no resistor.
Parameters
pinId Pin identifier
mode Resistor mode to set
Definition at line 29 of file pinconfig.c.
References LPC_GPIO_NUM_PINS.
Referenced by ADC_Init().
PINCFG_OpenDrainMode()
void PINCFG_OpenDrainMode (PIN_ValueType pinId, PINCFG_OpenDrainModeType mode)
Configures the open-drain mode of the specified pin.
      This updates the bits in the PINMODE_OD registers to enable or disable open-drain mode.
Parameters
pinId Pin identifier
mode Open-drain mode to set (NORMAL or OPEN_DRAIN)
Definition at line 42 of file pinconfig.c.
References LPC_GPIO_NUM_PINS.