MQTT
Provides the core capabilities for MQTT related functions.
Data Structures
struct MQTT_Item
Structure for storing MQTT payload data.
Typedefs
typedef void(* MQTT_ConfigCallback) (const char *payload, int len)
Callback function type for processing attributes received via MQTT.
Enumerations
enum MQTT_StateValueType {
MQTT_STATE_INIT
, MQTT_STATE_CONNECT
, MQTT_STATE_WAIT_CONNECT
, MQTT_STATE_SUBSCRIBE
,
MQTT_STATE_WAIT_SUBACK
, MQTT_STATE_PUBLISH
 }
Represents the internal state of the MQTT client.
enum MQTT_StatusValueType { MQTT_IDLE
, MQTT_PROCESSING
 }
Internal status of the MQTT client.
Functions
void MQTT_Init (MQTT_ConfigCallback callback)
Initializes the MQTT task.
bool MQTT_Ready (void)
Checks whether the MQTT task is ready.
bool MQTT_isReadyToPublish (void)
Checks whether the MQTT task is ready to publish a message.
void MQTT_Publish (const char *payload)
Publishes a pre-formatted JSON payload to the MQTT broker.
void MQTT_NoisePublish (float noiseValue, time_t time)
Publishes noise measurement data to the MQTT broker.
MQTT_StatusValueType MQTT_GetStatus (void)
Retrieves the current status of the MQTT client.
MQTT_StateValueType MQTT_GetState (void)
Retrieves the current internal state of the MQTT client state machine.
void MQTT_Resume (void)
Resume the MQTT task after Wi-Fi connection is established.
Detailed Description
Provides the core capabilities for MQTT related functions.
Typedef Documentation
MQTT_ConfigCallback
typedef void(* MQTT_ConfigCallback) (const char *payload, int len)
Callback function type for processing attributes received via MQTT.
      This function is called when a message is received on the topic
      "v1/devices/me/attributes", allowing the user to handle attribute updates
      sent by the server (ThingsBoard).
Parameters
payload Pointer to the received data buffer.
len Length (in bytes) of the content available in payload.
Definition at line 70 of file mqtt.h.
Enumeration Type Documentation
MQTT_StateValueType
enum MQTT_StateValueType
Represents the internal state of the MQTT client.
      This enumeration defines the states used in the MQTT task's state machine,
      guiding the process from connection initialization to publishing and
      handling attribute updates.
Enumerator
MQTT_STATE_INIT Initial state, waiting for Wi-Fi connection or ready to connect to broker
MQTT_STATE_CONNECT Attempting to send MQTT CONNECT packet
MQTT_STATE_WAIT_CONNECT Waiting for CONNACK response from the MQTT broker
MQTT_STATE_SUBSCRIBE Sending SUBSCRIBE packet to subscribe to desired topics
MQTT_STATE_WAIT_SUBACK Waiting for SUBACK response from the MQTT broker
MQTT_STATE_PUBLISH Ready to publish data to the MQTT broker and handle incoming attribute updates
Definition at line 80 of file mqtt.h.
MQTT_StatusValueType
enum MQTT_StatusValueType
Internal status of the MQTT client.
Enumerator
MQTT_IDLE MQTT client is idle or ready for a new request
MQTT_PROCESSING MQTT client is processing a mqtt request
Definition at line 104 of file mqtt.h.
Function Documentation
MQTT_GetState()
MQTT_StateValueType MQTT_GetState (void)
Retrieves the current internal state of the MQTT client state machine.
   Returns the current operational state of the MQTT client, indicating
   whether it is initializing, attempting to connect, waiting for a response,
   or ready to publish. This function is thread-safe and uses a FreeRTOS mutex
   to ensure consistent access.
Returns
The current state of the MQTT client as a value of MQTT_StateValueType.
Return values
MQTT_STATE_INIT Initial state, waiting for Wi-Fi or ready to initiate connection.
MQTT_STATE_CONNECT Attempting to send an MQTT CONNECT packet.
MQTT_STATE_WAIT_CONNECT Waiting for CONNACK response from the broker.
MQTT_STATE_PUBLISH Ready to publish data to the MQTT broker.
Definition at line 414 of file mqtt.c.
References MQTT_STATE_INIT.
Referenced by MQTT_isReadyToPublish().
MQTT_GetStatus()
MQTT_StatusValueType MQTT_GetStatus (void)
Retrieves the current status of the MQTT client.
   Returns the internal status of the MQTT client in a thread-safe manner
   by using a FreeRTOS mutex.
Returns
The current MQTT client status as a value of MQTT_StatusValueType.
Return values
MQTT_IDLE If the client is idle or ready for a new request.
MQTT_PROCESSING If the client is currently processing an MQTT request.
Definition at line 403 of file mqtt.c.
References MQTT_IDLE.
Referenced by WIFI_RequestExpected(), WIFI_RequestInfo(), WIFI_RequestPacketTransaction(), WIFI_RequestReceive(), and WIFI_RequestSendPacket().
MQTT_Init()
void MQTT_Init (MQTT_ConfigCallback callback)
Initializes the MQTT task.
   Creates a FreeRTOS mutex, queue, and task for managing MQTT operations.
   The MQTT task handles connection to the broker, publishing messages,
   and session maintenance according to the MQTT protocol.
Note
This function should be called after the Wi-Fi system is initialized, as it depends on an active TCP connection managed by the Wi-Fi driver.
Definition at line 358 of file mqtt.c.
Referenced by WIFI_Init().
MQTT_isReadyToPublish()
bool MQTT_isReadyToPublish (void)
Checks whether the MQTT task is ready to publish a message.
      This function returns true if the MQTT task is in the PUBLISH state,
      indicating that it is ready to send a new message to the MQTT broker.
Returns
true if ready to publish; false otherwise.
Definition at line 375 of file mqtt.c.
References MQTT_GetState(), and MQTT_STATE_PUBLISH.
Referenced by MQTT_Publish().
MQTT_NoisePublish()
void MQTT_NoisePublish (float noiseValue, time_t time)
Publishes noise measurement data to the MQTT broker.
   Formats the noise value and timestamp into a JSON payload and
   sends it using MQTT_Publish.
Parameters
noiseValue The noise measurement as a float.
time The timestamp associated with the measurement.
Definition at line 393 of file mqtt.c.
References MQTT_Publish().
MQTT_Publish()
void MQTT_Publish (const char * payload)
Publishes a pre-formatted JSON payload to the MQTT broker.
      This function sends a JSON-formatted string to the MQTT transmission queue
      if the system is in a state ready to publish. The message will be processed
      and transmitted by the MQTT task.
Parameters
payload The JSON-formatted string to publish.
Definition at line 379 of file mqtt.c.
References MQTT_isReadyToPublish().
Referenced by MQTT_NoisePublish().
MQTT_Ready()
bool MQTT_Ready (void)
Checks whether the MQTT task is ready.
   Indicates whether the MQTT task has been successfully created and is running.
Returns
true if MQTT task handle is valid; false otherwise.
Definition at line 371 of file mqtt.c.
MQTT_Resume()
void MQTT_Resume (void)
Resume the MQTT task after Wi-Fi connection is established.
      This function notifies the MQTT task to resume its operation
      after a successful Wi-Fi connection and configuration.
      By resuming the MQTT task, this function allows the MQTT client to proceed with
      connecting to the broker, subscribing to topics, and publishing messages.
Note
If the MQTT task handle is not valid this function has no effect.
Definition at line 425 of file mqtt.c.