DELAY
Provides the core capabilities for time delaying functions.
Macros
#define SYSTICK_FREQ (SystemCoreClock/1000)
Macro that defines the SysTick frequency as 1 ms.
Functions
bool DELAY_GetTimer2State (void)
Returns whether Timer2 has been initialized.
bool DELAY_GetSystickState (void)
Returns whether SysTick has been initialized.
int DELAY_Init (void)
Initializes the SysTick delay system.
void DELAY_Milliseconds (uint32_t millis)
Delays the execution for a given number of milliseconds.
uint32_t DELAY_GetElapsedMillis (uint32_t start)
Returns the number of milliseconds that have elapsed since a start point.
void DELAY_StopwatchInit (void)
Initializes the Timer2 stopwatch for microsecond precision delays.
void DELAY_Stopwatch (uint32_t waitUs)
Delays the execution for a given number of microseconds.
Detailed Description
Provides the core capabilities for time delaying functions.
Macro Definition Documentation
SYSTICK_FREQ
#define SYSTICK_FREQ (SystemCoreClock/1000)
Macro that defines the SysTick frequency as 1 ms.
SYSTICK_FREQ = (SystemCoreClock / 1000)
Definition at line 36 of file delay.h.
Referenced by DELAY_Init().
Function Documentation
DELAY_GetElapsedMillis()
uint32_t DELAY_GetElapsedMillis (uint32_t start)
Returns the number of milliseconds that have elapsed since a start point.
Parameters
start The starting value returned by SYSTICK_GetValue().
Returns
Elapsed milliseconds.
Definition at line 46 of file delay.c.
References SYSTICK_GetValue().
DELAY_GetSystickState()
bool DELAY_GetSystickState (void)
Returns whether SysTick has been initialized.
Returns
true if SysTick is initialized, false otherwise.
Definition at line 25 of file delay.c.
DELAY_GetTimer2State()
bool DELAY_GetTimer2State (void)
Returns whether Timer2 has been initialized.
Returns
true if Timer2 is initialized, false otherwise.
Definition at line 21 of file delay.c.
DELAY_Init()
int DELAY_Init (void)
Initializes the SysTick delay system.
Returns
0 if initialization was successful, -1 otherwise.
Definition at line 29 of file delay.c.
References SYSTICK_FREQ, and SYSTICK_Init().
DELAY_Milliseconds()
void DELAY_Milliseconds (uint32_t millis)
Delays the execution for a given number of milliseconds.
Parameters
millis Number of milliseconds to wait.
Definition at line 38 of file delay.c.
References SYSTICK_GetValue().
DELAY_Stopwatch()
void DELAY_Stopwatch (uint32_t waitUs)
Delays the execution for a given number of microseconds.
Parameters
waitUs Number of microseconds to wait.
Definition at line 57 of file delay.c.
References TIMER2_StopWatch().
Referenced by BUZZER_Alarm().