LED
Provides the core capabilities for led related functions.
Enumerations
enum LedModelEnum { LED_MODEL_ACTIVE_HIGH
, LED_MODEL_ACTIVE_LOW
 }
Enumeration of LED driving logic models.
enum LedColorEnum
Enumeration of LED colors and types.
Functions
void LED_Init (LED_ColorValueType ledColorId, bool state, LED_ModelType model)
Initializes an LED with the specified color, initial state, and control model.
bool LED_GetState (LED_ColorValueType ledColorId)
Gets the current state of the specified LED.
void LED_On (LED_ColorValueType ledColorId, LED_ModelType model)
Turns ON the specified LED according to its control model.
void LED_Off (LED_ColorValueType ledColorId, LED_ModelType model)
Turns OFF the specified LED according to its control model.
void LED_Toggle (LED_ColorValueType ledColorId, LED_ModelType model)
Toggles the state of the specified LED (ON to OFF or OFF to ON).
int LED_GetLedByColor (LED_ColorValueType ledColorId)
Returns the hardware pin number associated with the specified LED color.
Detailed Description
Provides the core capabilities for led related functions.
Enumeration Type Documentation
LedColorEnum
enum LedColorEnum
Enumeration of LED colors and types.
      Represents the color and category of LEDs used in the system.
Definition at line 47 of file led.h.
LedModelEnum
enum LedModelEnum
Enumeration of LED driving logic models.
      Defines how the LED is controlled electrically.
Enumerator
LED_MODEL_ACTIVE_HIGH LED is ON when output is HIGH
LED_MODEL_ACTIVE_LOW LED is ON when output is LOW
Definition at line 36 of file led.h.
Function Documentation
LED_GetLedByColor()
int LED_GetLedByColor (LED_ColorValueType ledColorId)
Returns the hardware pin number associated with the specified LED color.
Parameters
ledColorId The color identifier of the LED.
Returns
The hardware pin number corresponding to the LED.
Definition at line 60 of file led.c.
Referenced by LED_GetState(), LED_Init(), LED_Off(), and LED_On().
LED_GetState()
bool LED_GetState (LED_ColorValueType ledColorId)
Gets the current state of the specified LED.
Parameters
ledColorId The color identifier of the LED.
Returns
true if the LED is ON; false otherwise.
Definition at line 31 of file led.c.
References LED_GetLedByColor(), and PIN_Value().
Referenced by LED_RTOS_GetState(), and LED_Toggle().
LED_Init()
void LED_Init (LED_ColorValueType ledColorId, bool state, LED_ModelType model)
Initializes an LED with the specified color, initial state, and control model.
Parameters
ledColorId The color identifier of the LED to initialize.
state The initial state of the LED (true for ON, false for OFF).
model The LED control model (active-high or active-low).
Definition at line 18 of file led.c.
References LED_GetLedByColor(), LED_Off(), LED_On(), PIN_Direction(), and PINCFG_Function().
Referenced by LED_RTOS_InitAllExt(), LED_RTOS_InitAllInt(), LED_RTOS_InitRedInt(), and LED_RTOS_InitSemaphore().
LED_Off()
void LED_Off (LED_ColorValueType ledColorId, LED_ModelType model)
Turns OFF the specified LED according to its control model.
Parameters
ledColorId The color identifier of the LED.
model The LED control model (active-high or active-low).
Definition at line 44 of file led.c.
References LED_GetLedByColor(), LED_MODEL_ACTIVE_LOW, PIN_Clear(), and PIN_Set().
Referenced by LED_Init(), and LED_Toggle().
LED_On()
void LED_On (LED_ColorValueType ledColorId, LED_ModelType model)
Turns ON the specified LED according to its control model.
Parameters
ledColorId The color identifier of the LED.
model The LED control model (active-high or active-low).
Definition at line 37 of file led.c.
References LED_GetLedByColor(), LED_MODEL_ACTIVE_LOW, PIN_Clear(), and PIN_Set().
Referenced by LED_Init(), and LED_Toggle().
LED_Toggle()
void LED_Toggle (LED_ColorValueType ledColorId, LED_ModelType model)
Toggles the state of the specified LED (ON to OFF or OFF to ON).
Parameters
ledColorId The color identifier of the LED.
model The LED control model (active-high or active-low).
Definition at line 51 of file led.c.
References LED_GetState(), LED_Off(), and LED_On().