MICROPHONE
Provides the core capabilities for MAX9814 FreeRTOS functions.
Functions
void MICROPHONE_Init (MAX9814_GainValueType gain)
Initializes the microphone module and creates the control mutex.
float MICROPHONE_Read (void)
Reads the current sound level in decibels (dB).
void MICROPHONE_SetGain (MAX9814_GainValueType gain)
Changes the gain level of the microphone.
Detailed Description
Provides the core capabilities for MAX9814 FreeRTOS functions.
Function Documentation
MICROPHONE_Init()
void MICROPHONE_Init (MAX9814_GainValueType gain)
Initializes the microphone module and creates the control mutex.
   This function creates a mutex to ensure thread-safe access to the microphone hardware.
   It then initializes the MAX9814 driver with the specified gain configuration.
   The gain can be changed later using MICROPHONE_SetGain().
Parameters
gain Initial gain setting for the MAX9814 microphone. Possible values:
MAX9814_VCC_GAIN (40 dB)
MAX9814_GND_GAIN (50 dB)
MAX9814_FLOAT_GAIN (60 dB)
Note
This function must be called before using any other MICROPHONE-related function.
Definition at line 21 of file microphone.c.
References MAX9814_Init().
MICROPHONE_Read()
float MICROPHONE_Read (void)
Reads the current sound level in decibels (dB).
   This function collects multiple ADC samples from the microphone,
   computes the RMS voltage, and converts it into a decibel value.
   Access to the microphone is controlled by a mutex to avoid concurrent interference.
Returns
Current sound level in decibels (dB).
Return values
-INFINITY If the RMS voltage is zero or below detection threshold.
>0 Valid sound level including microphone gain compensation.
Note
The function blocks execution until the mutex is available for safe reading.
Definition at line 30 of file microphone.c.
References MAX9814_Read().
MICROPHONE_SetGain()
void MICROPHONE_SetGain (MAX9814_GainValueType gain)
Changes the gain level of the microphone.
   This function adjusts the analog gain of the MAX9814 microphone by configuring
   the gain control pin. It also updates the internal dB compensation value
   used when converting voltage to decibels.
   The access is protected by a mutex to ensure safe concurrent operation.
Parameters
gain Gain setting to apply. Options:
MAX9814_VCC_GAIN (40 dB)
MAX9814_GND_GAIN (50 dB)
MAX9814_FLOAT_GAIN (60 dB)
Note
The function blocks execution until the mutex is available for safe configuration.
Definition at line 43 of file microphone.c.
References MAX9814_SetGain().