BUZZER_FreeRTOS
Provides the core capabilities for Buzzer FreeRTOS related functions.
Enumerations
enum BUZZER_Command { BUZZER_CMD_ON = 0x01
, BUZZER_CMD_OFF = 0x02
, BUZZER_CMD_ALARM = 0x03
 }
Enumeration representing buzzer command types.
Functions
void BUZZER_RTOS_Init (void)
Initializes the buzzer task.
void BUZZER_RTOS_Task (void *pvParameters)
FreeRTOS task responsible for controlling the buzzer.
void BUZZER_RTOS_On (void)
Sends command to turn the buzzer on.
void BUZZER_RTOS_Off (void)
Sends command to turn the buzzer off.
void BUZZER_RTOS_Alarm (uint32_t duration)
Sends command to activate the buzzer alarm mode.
Detailed Description
Provides the core capabilities for Buzzer FreeRTOS related functions.
Enumeration Type Documentation
BUZZER_Command
enum BUZZER_Command
Enumeration representing buzzer command types.
   This enum defines the possible actions that can be sent
   to the buzzer task, such as turning it ON, OFF or triggering an alarm.
Enumerator
BUZZER_CMD_ON Turn the buzzer ON.
BUZZER_CMD_OFF Turn the buzzer OFF.
BUZZER_CMD_ALARM Trigger an alarm for a specific duration.
Definition at line 35 of file buzzer_rtos.h.
Function Documentation
BUZZER_RTOS_Alarm()
void BUZZER_RTOS_Alarm (uint32_t duration)
Sends command to activate the buzzer alarm mode.
   This function notifies the buzzer task to activate alarm mode
   for a specified duration.
Parameters
duration Alarm duration (milliseconds).
Definition at line 116 of file buzzer_rtos.c.
References BUZZER_CMD_ALARM.
BUZZER_RTOS_Init()
void BUZZER_RTOS_Init (void)
Initializes the buzzer task.
   This function creates the task responsible for controlling the buzzer state
   (on, off, or alarm) based on received notifications.
Note
This function must be called before accessing any Buzzer-related function.
Definition at line 59 of file buzzer_rtos.c.
References BUZZER_RTOS_Task().
BUZZER_RTOS_Off()
void BUZZER_RTOS_Off (void)
Sends command to turn the buzzer off.
   This function notifies the buzzer task to turn it off.
Definition at line 112 of file buzzer_rtos.c.
References BUZZER_CMD_OFF.
BUZZER_RTOS_On()
void BUZZER_RTOS_On (void)
Sends command to turn the buzzer on.
   This function notifies the buzzer task to turn it on.
Definition at line 108 of file buzzer_rtos.c.
References BUZZER_CMD_ON.
BUZZER_RTOS_Task()
void BUZZER_RTOS_Task (void * pvParameters)
FreeRTOS task responsible for controlling the buzzer.
   The task waits for notifications containing commands to turn the buzzer
   on, off, or activate alarm mode.
Parameters
pvParameters Task parameter (not used).
Note
The task must be initialized using "BUZZER_RTOS_Init()".
Definition at line 64 of file buzzer_rtos.c.
References BUZZER_CMD_ALARM, BUZZER_CMD_OFF, BUZZER_CMD_ON, BUZZER_Init(), BUZZER_Off(), and BUZZER_On().
Referenced by BUZZER_RTOS_Init().