ADC
Provides the core capabilities for ADC configuration functions.
Functions
void ADC_Init (uint8_t channel)
Initializes the ADC on the specified channel.
uint16_t ADC_Read (uint8_t channel)
Performs a blocking ADC read on the specified channel.
Detailed Description
Provides the core capabilities for ADC configuration functions.
Function Documentation
ADC_Init()
void ADC_Init (uint8_t channel)
Initializes the ADC on the specified channel.
      Powers up the ADC peripheral, configures the ADC clock, and sets the appropriate pin function
      for the selected channel.
Parameters
channel ADC channel to initialize (range: 0 to 7).
Definition at line 18 of file adc.c.
References NONE, PINCFG_Function(), and PINCFG_Mode().
Referenced by MAX9814_Init().
ADC_Read()
uint16_t ADC_Read (uint8_t channel)
Performs a blocking ADC read on the specified channel.
      Starts a single ADC conversion and waits until the result is ready.
Parameters
channel ADC channel to read from (range: 0 to 7).
Returns
12-bit digital value from the ADC conversion (range: 0 to 4095).
Note
This function performs a blocking read. It waits until the conversion is complete.
Definition at line 62 of file adc.c.
Referenced by MAX9814_Read().