RTC
Provides the core capabilities for rtc functions.
Macros
#define RTC_PCONP_ENABLE 9
#define CLKEN_BIT_POS 0
#define CTIME_SEC_MASK 0x3F
#define CTIME_MIN_MASK 0x3F00
#define CTIME_HOUR_MASK 0x1F0000
#define CTIME_DOW_MASK 0x7000000
#define CTIME_DOM_MASK 0x1F
#define CTIME_MONTH_MASK 0xF00
#define CTIME_YEAR_MASK 0xFFF0000
#define CTIME_DOY_MASK 0xFFF
Functions
int compareByTime (const struct tm *a, const struct tm *b)
Compares the time (hours, minutes, seconds) of two struct tm values.
void RTC_Init (time_t seconds)
Initializes the RTC with a timestamp (seconds since 1970-01-01 00:00).
void RTC_GetTimeDate (struct tm *dateTime)
Retrieves current date and time from the RTC.
void RTC_SetTimeDate (struct tm *dateTime)
Sets the RTC with a full date and time from a struct tm.
void RTC_SetSeconds (time_t seconds)
Sets the RTC time using seconds since the Unix epoch (1970-01-01 00:00).
time_t RTC_GetSeconds (void)
Gets the number of seconds since 1970-01-01 00:00 from RTC.
Detailed Description
Provides the core capabilities for rtc functions.
Macro Definition Documentation
CLKEN_BIT_POS
#define CLKEN_BIT_POS 0
Bit position for clock enable in CCR
Definition at line 30 of file rtc.h.
Referenced by RTC_Init(), and RTC_SetTimeDate().
CTIME_DOM_MASK
#define CTIME_DOM_MASK 0x1F
Mask for day of month in CTIME1 (bits 0–4)
Definition at line 35 of file rtc.h.
Referenced by RTC_GetTimeDate().
CTIME_DOW_MASK
#define CTIME_DOW_MASK 0x7000000
Mask for day of week in CTIME0 (bits 24–26)
Definition at line 34 of file rtc.h.
Referenced by RTC_GetTimeDate().
CTIME_DOY_MASK
#define CTIME_DOY_MASK 0xFFF
Mask for day of year in CTIME2 (bits 0–11)
Definition at line 38 of file rtc.h.
Referenced by RTC_GetTimeDate().
CTIME_HOUR_MASK
#define CTIME_HOUR_MASK 0x1F0000
Mask for hours in CTIME0 (bits 16–20)
Definition at line 33 of file rtc.h.
Referenced by RTC_GetTimeDate().
CTIME_MIN_MASK
#define CTIME_MIN_MASK 0x3F00
Mask for minutes in CTIME0 (bits 8–13)
Definition at line 32 of file rtc.h.
Referenced by RTC_GetTimeDate().
CTIME_MONTH_MASK
#define CTIME_MONTH_MASK 0xF00
Mask for month in CTIME1 (bits 8–11)
Definition at line 36 of file rtc.h.
Referenced by RTC_GetTimeDate().
CTIME_SEC_MASK
#define CTIME_SEC_MASK 0x3F
Mask for seconds in CTIME0 (bits 0–5)
Definition at line 31 of file rtc.h.
Referenced by RTC_GetTimeDate().
CTIME_YEAR_MASK
#define CTIME_YEAR_MASK 0xFFF0000
Mask for year in CTIME1 (bits 16–27)
Definition at line 37 of file rtc.h.
Referenced by RTC_GetTimeDate().
RTC_PCONP_ENABLE
#define RTC_PCONP_ENABLE 9
Power Control bit position for RTC in PCONP
Definition at line 29 of file rtc.h.
Referenced by RTC_Init().
Function Documentation
compareByTime()
int compareByTime (const struct tm * a, const struct tm * b)
Compares the time (hours, minutes, seconds) of two struct tm values.
      Compares only the time portion (ignores date) between structures.
Parameters
a Pointer to time structure A.
b Pointer to time structure B.
Returns
Integer result: negative if A < B, positive if A > B, zero if equal.
Definition at line 18 of file rtc.c.
Referenced by RTC_SetTimeDate().
RTC_GetSeconds()
time_t RTC_GetSeconds (void)
Gets the number of seconds since 1970-01-01 00:00 from RTC.
      Reads current RTC time, fills struct tm, and converts it to time_t.
Returns
Seconds since Unix epoch.
Definition at line 83 of file rtc.c.
References RTC_GetTimeDate().
Referenced by CLOCK_GetSeconds().
RTC_GetTimeDate()
void RTC_GetTimeDate (struct tm * dateTime)
Retrieves current date and time from the RTC.
      Populates a given struct tm with the current values read from CTIME registers.
Parameters
dateTime Pointer to a struct tm to be filled with RTC values.
Definition at line 37 of file rtc.c.
References CTIME_DOM_MASK, CTIME_DOW_MASK, CTIME_DOY_MASK, CTIME_HOUR_MASK, CTIME_MIN_MASK, CTIME_MONTH_MASK, CTIME_SEC_MASK, and CTIME_YEAR_MASK.
Referenced by CLOCK_GetTimeDate(), RTC_GetSeconds(), and RTC_SetTimeDate().
RTC_Init()
void RTC_Init (time_t seconds)
Initializes the RTC with a timestamp (seconds since 1970-01-01 00:00).
      Enables RTC power, disables the clock during setup, sets time,
      and then starts the RTC clock.
Parameters
seconds Seconds since Unix epoch (1970-01-01 00:00).
Definition at line 27 of file rtc.c.
References CLKEN_BIT_POS, RTC_PCONP_ENABLE, and RTC_SetSeconds().
Referenced by CLOCK_Init().
RTC_SetSeconds()
void RTC_SetSeconds (time_t seconds)
Sets the RTC time using seconds since the Unix epoch (1970-01-01 00:00).
      Converts the seconds to a struct tm using localtime() and sets the RTC.
Parameters
seconds Seconds since Unix epoch.
Definition at line 76 of file rtc.c.
References RTC_SetTimeDate().
Referenced by CLOCK_SetSeconds(), and RTC_Init().
RTC_SetTimeDate()
void RTC_SetTimeDate (struct tm * dateTime)
Sets the RTC with a full date and time from a struct tm.
      Attempts to apply the desired date/time repeatedly until RTC reflects it.
      The clock is stopped during updates and re-enabled after.
Parameters
dateTime Pointer to struct tm containing desired time and date.
Definition at line 53 of file rtc.c.
References CLKEN_BIT_POS, compareByTime(), and RTC_GetTimeDate().
Referenced by CLOCK_SetTimeDate(), and RTC_SetSeconds().