CLOCK
Provides the core capabilities for RTC FreeRTOS functions.
Functions
void CLOCK_Init (void)
Initializes the RTC module and creates the control mutex.
void CLOCK_GetTimeDate (struct tm *dateTime)
Retrieves the current date and time from the RTC.
void CLOCK_SetTimeDate (struct tm *dateTime)
Sets the date and time in the RTC.
void CLOCK_SetSeconds (time_t seconds)
Sets the absolute time in seconds since 1970 (Epoch).
time_t CLOCK_GetSeconds (void)
Gets the current RTC time in seconds since 1970 (Epoch).
Detailed Description
Provides the core capabilities for RTC FreeRTOS functions.
Function Documentation
CLOCK_GetSeconds()
time_t CLOCK_GetSeconds (void)
Gets the current RTC time in seconds since 1970 (Epoch).
   Returns the current time value in seconds since the Unix Epoch (1970-01-01).
   Read access is protected by a mutex to prevent interference from other tasks.
Returns
Current time in seconds since 1970-01-01.
Return values
0 If the RTC is at the initial date or not initialized.
>0 Valid time value.
Note
The function blocks execution until the mutex is available for safe reading.
Definition at line 59 of file clock.c.
References RTC_GetSeconds().
CLOCK_GetTimeDate()
void CLOCK_GetTimeDate (struct tm * dateTime)
Retrieves the current date and time from the RTC.
   The function uses a mutex to ensure exclusive access to the RTC,
   preventing interference from other tasks. The date and time values
   are filled into the provided "struct tm".
Parameters
dateTime Pointer to the "struct tm" structure where date and time will be stored.
Note
The function blocks execution until the mutex is available for safe reading.
Definition at line 32 of file clock.c.
References RTC_GetTimeDate().
CLOCK_Init()
void CLOCK_Init (void)
Initializes the RTC module and creates the control mutex.
   This function checks if the RTC mutex has been properly created, and if not,
   it creates it before initializing the RTC. The mutex is used to protect
   concurrent access to the RTC.
Note
This function must be called before accessing any RTC-related function.
Definition at line 23 of file clock.c.
References RTC_Init().
CLOCK_SetSeconds()
void CLOCK_SetSeconds (time_t seconds)
Sets the absolute time in seconds since 1970 (Epoch).
   This function updates the RTC with the provided value in seconds.
   Access is protected by a mutex to ensure no other task interferes during the update.
Parameters
seconds Absolute time in seconds since 1970-01-01 (Epoch).
Note
The function blocks execution until the mutex is available for safe writing.
Definition at line 50 of file clock.c.
References RTC_SetSeconds().
CLOCK_SetTimeDate()
void CLOCK_SetTimeDate (struct tm * dateTime)
Sets the date and time in the RTC.
   This function sets the system date and time, protecting access to the RTC with a mutex.
   It ensures that only one task has exclusive access to the RTC during the operation.
Parameters
dateTime Pointer to the "struct tm" structure containing the date and time to be set.
Note
The function blocks execution until the mutex is available for safe writing.
Definition at line 41 of file clock.c.
References RTC_SetTimeDate().