WIFI
Provides the core capabilities for Wi-Fi related functions.
Data Structures
struct WIFI_Config
Configuration structure for initializing Wi-Fi and related services.
struct WIFI_Info
Structure used to hold the IP and MAC address of the Wi-Fi module.
struct WIFI_QueueItem
Structure used to send commands via queue to the Wi-Fi task.
Typedefs
typedef bool(* WIFI_ParserFunc) (const char *buffer, void *user_data)
Function pointer for parser callbacks.
Enumerations
enum WIFI_StateValueType { WIFI_STATE_DISCONNECTED
, WIFI_STATE_CONNECTED
, WIFI_STATE_ERROR
 }
Enumeration of possible Wi-Fi states.
enum WIFI_ResultValueType { WIFI_RESULT_NONE
, WIFI_RESULT_SUCCESS
, WIFI_RESULT_ERROR
 }
Result of the last Wi-Fi command executed.
enum WIFI_CommandValueType {
WIFI_CMD_DISCONNECT
, WIFI_CMD_CONNECT
, WIFI_CMD_GET_INFO
, WIFI_CMD_GET_EXPECTED
,
WIFI_CMD_SEND
, WIFI_CMD_RECEIVE
, WIFI_CMD_TRANSACTION
 }
Enumeration of commands for Wi-Fi task operations.
enum WIFI_ServiceValueType { WIFI_SERVICE_NONE
, WIFI_SERVICE_NTP
, WIFI_SERVICE_MQTT
, WIFI_SERVICE_BOTH
 }
Specifies which service(s) to initialize along with Wi-Fi.
enum WIFI_ConnectionModeValueType { WIFI_SINGLE_CONNECTION
, WIFI_MULTIPLE_CONNECTION
 }
Defines the connection mode for the ESP Wi-Fi module.
Functions
void WIFI_Init (WIFI_Config *config)
Initializes the Wi-Fi module and optionally related services.
bool WIFI_Ready (void)
Checks whether the Wi-Fi task is ready.
void WIFI_Connect (void)
Triggers a connection attempt to the configured Wi-Fi network.
void WIFI_Disconnect (void)
Disconnects from the current Wi-Fi network.
bool WIFI_RequestInfo (void)
Requests the current IP and MAC addresses from the module.
bool WIFI_RequestExpected (char *command, char *expected, int timeout_ms)
Sends a custom AT command and checks for an expected response.
bool WIFI_RequestSendPacket (char *command, uint8_t *data, int length, int timeout_ms)
Sends a raw data packet to the Wi-Fi module.
bool WIFI_RequestReceive (int timeout_ms, WIFI_ParserFunc parser_recv, void *uData)
Receives a response from the Wi-Fi module with a custom parser.
bool WIFI_RequestPacketTransaction (char *command, uint8_t *data, int length, int timeout_ms, WIFI_ParserFunc parser_recv, void *uData)
Performs an atomic transaction (send followed by receive).
WIFI_ConnectionModeValueType WIFI_GetCIPMUX (void)
Returns the current CIPMUX (connection mode) setting.
WIFI_StateValueType WIFI_GetState (void)
Retrieves the current state of the Wi-Fi connection.
WIFI_ResultValueType WIFI_GetResult (void)
Returns the result of the last Wi-Fi command.
bool WIFI_GetSavedIP (char *buffer)
Copies the last saved IP address into the provided buffer.
bool WIFI_GetSavedMAC (char *buffer)
Copies the last saved MAC address into the provided buffer.
bool WIFI_WaitConnect (void)
Waits for the WiFi connection process to complete.
bool WIFI_WaitDisconnect (void)
Waits for the WiFi disconnection process to complete.
bool WIFI_WaitIP (char *buffer)
Waits for a valid IP address to be acquired.
bool WIFI_WaitMAC (char *buffer)
Waits for a valid MAC address to be acquired.
Detailed Description
Provides the core capabilities for Wi-Fi related functions.
Typedef Documentation
WIFI_ParserFunc
typedef bool(* WIFI_ParserFunc) (const char *buffer, void *user_data)
Function pointer for parser callbacks.
Parameters
buffer The input buffer to parse.
user_data Pointer to user data or storage.
Return values
true if expected data is found or parsed.
false otherwise.
Definition at line 65 of file wifi.h.
Enumeration Type Documentation
WIFI_CommandValueType
enum WIFI_CommandValueType
Enumeration of commands for Wi-Fi task operations.
Enumerator
WIFI_CMD_DISCONNECT Disconnect from Wi-Fi network
WIFI_CMD_CONNECT Connect to Wi-Fi network
WIFI_CMD_GET_INFO Request the IP and MAC address
WIFI_CMD_GET_EXPECTED Send command and wait for expected response
WIFI_CMD_SEND Send command or data packet
WIFI_CMD_RECEIVE Receive a data packet
WIFI_CMD_TRANSACTION Send and then receive as a single transaction.
Definition at line 91 of file wifi.h.
WIFI_ConnectionModeValueType
enum WIFI_ConnectionModeValueType
Defines the connection mode for the ESP Wi-Fi module.
Enumerator
WIFI_SINGLE_CONNECTION Single connection mode (CIPMUX=0)
WIFI_MULTIPLE_CONNECTION Multiple connection mode (CIPMUX=1)
Definition at line 116 of file wifi.h.
WIFI_ResultValueType
enum WIFI_ResultValueType
Result of the last Wi-Fi command executed.
Enumerator
WIFI_RESULT_NONE No result available
WIFI_RESULT_SUCCESS Command executed successfully
WIFI_RESULT_ERROR Command execution failed
Definition at line 81 of file wifi.h.
WIFI_ServiceValueType
enum WIFI_ServiceValueType
Specifies which service(s) to initialize along with Wi-Fi.
Enumerator
WIFI_SERVICE_NONE Do not initialize any service
WIFI_SERVICE_NTP Initialize only NTP service
WIFI_SERVICE_MQTT Initialize only MQTT service
WIFI_SERVICE_BOTH Initialize both NTP and MQTT services
Definition at line 105 of file wifi.h.
WIFI_StateValueType
enum WIFI_StateValueType
Enumeration of possible Wi-Fi states.
Enumerator
WIFI_STATE_DISCONNECTED Not connected to a Wi-Fi network
WIFI_STATE_CONNECTED Successfully connected to a Wi-Fi network
WIFI_STATE_ERROR Error occurred during Wi-Fi operations
Definition at line 71 of file wifi.h.
Function Documentation
WIFI_Connect()
void WIFI_Connect (void)
Triggers a connection attempt to the configured Wi-Fi network.
   This function signals the internal Wi-Fi task to begin the connection
   process using the SSID and password previously provided via WIFI_Init.
Definition at line 296 of file wifi.c.
References WIFI_CMD_CONNECT.
Referenced by WIFI_WaitConnect().
WIFI_Disconnect()
void WIFI_Disconnect (void)
Disconnects from the current Wi-Fi network.
      This function sends the appropriate AT command to disconnect the ESP module
      from the Wi-Fi access point and updates the internal connection state.
Definition at line 303 of file wifi.c.
References WIFI_CMD_DISCONNECT.
Referenced by WIFI_WaitDisconnect().
WIFI_GetCIPMUX()
WIFI_ConnectionModeValueType WIFI_GetCIPMUX (void)
Returns the current CIPMUX (connection mode) setting.
      This function retrieves the current connection mode used by the Wi-Fi module.
      It indicates whether the module is configured for single or multiple TCP/UDP connections.
Returns
The current connection mode as a value of WIFI_ConnectionModeValueType.
Return values
WIFI_SINGLE_CONNECTION If the module is configured for a single connection (CIPMUX=0).
WIFI_MULTIPLE_CONNECTION If the module is configured for multiple connections (CIPMUX=1).
Definition at line 401 of file wifi.c.
WIFI_GetResult()
WIFI_ResultValueType WIFI_GetResult (void)
Returns the result of the last Wi-Fi command.
      This function retrieves the result of the last command handled by the Wi-Fi task.
Returns
The current result as a value of WIFI_ResultValueType.
Return values
WIFI_RESULT_NONE No result available yet.
WIFI_RESULT_SUCCESS The last command completed successfully.
WIFI_RESULT_ERROR The last command failed or timed out.
Definition at line 416 of file wifi.c.
References WIFI_RESULT_NONE.
Referenced by WIFI_WaitIP(), and WIFI_WaitMAC().
WIFI_GetSavedIP()
bool WIFI_GetSavedIP (char * buffer)
Copies the last saved IP address into the provided buffer.
      This function retrieves the last IP address successfully obtained
      from the ESP module and copies it to the user-provided buffer.
Parameters
buffer Pointer to a character buffer where the IP string will be copied. Must be at least WIFI_MAX_IPv4_LENGTH bytes in size.
Return values
true If the IP address was successfully copied.
false If the buffer is NULL or the mutex could not be acquired.
Definition at line 427 of file wifi.c.
Referenced by WIFI_WaitIP().
WIFI_GetSavedMAC()
bool WIFI_GetSavedMAC (char * buffer)
Copies the last saved MAC address into the provided buffer.
      This function retrieves the last MAC address successfully obtained
      from the ESP module and copies it to the user-provided buffer.
Parameters
buffer Pointer to a character buffer where the MAC string will be copied. Must be at least WIFI_MAX_MAC_LENGTH bytes in size.
Return values
true If the MAC address was successfully copied.
false If the buffer is NULL or the mutex could not be acquired.
Definition at line 441 of file wifi.c.
Referenced by WIFI_WaitMAC().
WIFI_GetState()
WIFI_StateValueType WIFI_GetState (void)
Retrieves the current state of the Wi-Fi connection.
   Returns the internally tracked connection state, ensuring thread safety
   by using a FreeRTOS mutex.
Returns
The current state as a value of WIFI_StateValueType.
Return values
WIFI_STATE_DISCONNECTED If the module is not connected.
WIFI_STATE_CONNECTED If the module is successfully connected.
WIFI_STATE_ERROR If an error occurred during the last operation.
Definition at line 405 of file wifi.c.
References WIFI_STATE_DISCONNECTED.
Referenced by WIFI_WaitConnect(), and WIFI_WaitDisconnect().
WIFI_Init()
void WIFI_Init (WIFI_Config * config)
Initializes the Wi-Fi module and optionally related services.
   This function stores the SSID and password used for connection,
   creates synchronization primitives, and starts the internal Wi-Fi task.
   It can also initialize NTP and/or MQTT services depending on the configuration.
Parameters
config Pointer to a WIFI_ConfigType structure containing the SSID, password, and service initialization options.
Note
The config pointer and its fields must not be NULL. SSID and password strings must remain valid during initialization.
Definition at line 259 of file wifi.c.
References MQTT_Init(), NTP_Init(), WIFI_Config::password, WIFI_Config::service, WIFI_Config::ssid, WIFI_MULTIPLE_CONNECTION, WIFI_SERVICE_BOTH, WIFI_SERVICE_MQTT, WIFI_SERVICE_NONE, WIFI_SERVICE_NTP, WIFI_SINGLE_CONNECTION, and WIFI_Config::xMQTT_ConfigCallback.
WIFI_Ready()
bool WIFI_Ready (void)
Checks whether the Wi-Fi task is ready.
   Indicates whether the Wi-Fi task has been successfully created and is running.
Return values
true If the Wi-Fi task is active.
false If the task is not yet created or has failed.
Definition at line 292 of file wifi.c.
WIFI_RequestExpected()
bool WIFI_RequestExpected (char * command, char * expected, int timeout_ms)
Sends a custom AT command and checks for an expected response.
      This function queues a custom command to be sent to the Wi-Fi module,
      and the task will wait for a response matching the given expected string.
Parameters
command The null-terminated AT command string to send.
expected The null-terminated string expected in the response.
timeout_ms Timeout in milliseconds to wait for the response.
Note
If the MQTT module is currently processing, this request will be ignored.
Return values
true If the command was successfully queued.
false If the MQTT module is busy or parameters are invalid.
Definition at line 324 of file wifi.c.
References MQTT_GetStatus(), MQTT_PROCESSING, WIFI_CMD_GET_EXPECTED, and WIFI_RESULT_NONE.
WIFI_RequestInfo()
bool WIFI_RequestInfo (void)
Requests the current IP and MAC addresses from the module.
      This function sends a command to the ESP module to retrieve the current assigned IP and MAC addresses.
      The result will be stored internally and can be retrieved with WIFI_GetSavedIP and WIFI_GetSavedMAC.
Note
If the MQTT module is currently processing, this request will be ignored.
Return values
true If the request was successfully queued.
false If the MQTT module is busy or the request could not be enqueued.
Definition at line 310 of file wifi.c.
References MQTT_GetStatus(), MQTT_PROCESSING, WIFI_CMD_GET_INFO, and WIFI_RESULT_NONE.
Referenced by WIFI_WaitIP(), and WIFI_WaitMAC().
WIFI_RequestPacketTransaction()
bool WIFI_RequestPacketTransaction (char * command, uint8_t * data, int length, int timeout_ms, WIFI_ParserFunc parser_recv, void * uData)
Performs an atomic transaction (send followed by receive).
   This function sends a data packet to the ESP module and waits for a response
   in a single queued transaction. It ensures that the send/receive operation is
   performed without interleaving.
Parameters
command The null-terminated AT command string to send.
data Pointer to the data to send.
length Length of the data to send (in bytes).
timeout_ms Timeout to wait for the response (in milliseconds).
parser_recv Parser function to process the response.
uData Pointer to user data or response buffer.
Return values
true If the transaction request was queued successfully.
false If the MQTT is currently busy or the queue is unavailable.
Definition at line 379 of file wifi.c.
References MQTT_GetStatus(), MQTT_PROCESSING, WIFI_CMD_TRANSACTION, and WIFI_RESULT_NONE.
WIFI_RequestReceive()
bool WIFI_RequestReceive (int timeout_ms, WIFI_ParserFunc parser_recv, void * uData)
Receives a response from the Wi-Fi module with a custom parser.
   This function is intended to be used while MQTT is actively processing.
   It enqueues a request to wait for a response from the ESP module and parse it
   using the provided parser function.
Parameters
timeout_ms Timeout in milliseconds to wait for the response.
parser_recv The parser function that will process the response.
uData User data or buffer that the parser will fill.
Return values
true If the receive request was queued successfully.
false If the MQTT is not in processing mode or the queue is unavailable.
Definition at line 361 of file wifi.c.
References MQTT_GetStatus(), MQTT_PROCESSING, WIFI_CMD_RECEIVE, and WIFI_RESULT_NONE.
WIFI_RequestSendPacket()
bool WIFI_RequestSendPacket (char * command, uint8_t * data, int length, int timeout_ms)
Sends a raw data packet to the Wi-Fi module.
   This function queues a request to send a buffer of bytes (e.g., MQTT/NTP data)
   to the ESP-01 module. The data will be transmitted by the internal Wi-Fi task.
Parameters
command The null-terminated AT command string to send.
data Pointer to the data packet to send.
length Number of bytes in the data packet.
timeout_ms Timeout in milliseconds to wait for the response.
Return values
true If the send request was queued successfully.
false If the MQTT layer is busy or the queue is unavailable.
Definition at line 342 of file wifi.c.
References MQTT_GetStatus(), MQTT_PROCESSING, WIFI_CMD_SEND, and WIFI_RESULT_NONE.
WIFI_WaitConnect()
bool WIFI_WaitConnect (void)
Waits for the WiFi connection process to complete.
   This function sends a connection request to the ESP-01 module
   (via "WIFI_Connect") and continuously polls the connection state
   until a successful connection is established or a timeout occurs.
Return values
true If the module reached WIFI_STATE_CONNECTED within the timeout.
false If the timeout was reached before a successful connection.
Definition at line 455 of file wifi.c.
References WIFI_Connect(), WIFI_GetState(), and WIFI_STATE_CONNECTED.
WIFI_WaitDisconnect()
bool WIFI_WaitDisconnect (void)
Waits for the WiFi disconnection process to complete.
   This function sends a disconnection request to the ESP-01 module
   (via "WIFI_Disconnect") and continuously polls the connection state
   until the module is fully disconnected or a timeout occurs.
Return values
true If the module reached WIFI_STATE_DISCONNECTED within the timeout.
false If the timeout was reached before the disconnection completed.
Definition at line 469 of file wifi.c.
References WIFI_Disconnect(), WIFI_GetState(), and WIFI_STATE_CONNECTED.
WIFI_WaitIP()
bool WIFI_WaitIP (char * buffer)
Waits for a valid IP address to be acquired.
   This function continuously polls the result of a previously requested
   IP acquisition (via "WIFI_RequestIP") until a valid IP address is received
   or a timeout occurs.
Parameters
buffer Pointer to a buffer where the valid IP address will be stored. Must be at least WIFI_MAX_IPv4_LENGTH bytes.
Return values
true If a valid IP address was retrieved.
false If the timeout was reached or an error occurred.
Definition at line 485 of file wifi.c.
References WIFI_GetResult(), WIFI_GetSavedIP(), WIFI_RequestInfo(), WIFI_RESULT_ERROR, and WIFI_RESULT_SUCCESS.
WIFI_WaitMAC()
bool WIFI_WaitMAC (char * buffer)
Waits for a valid MAC address to be acquired.
   This function continuously polls the result of a previously requested
   MAC acquisition (via "WIFI_RequestMAC") until a valid MAC address is received
   or a timeout occurs.
Parameters
buffer Pointer to a buffer where the valid MAC address will be stored. Must be at least WIFI_MAX_MAC_LENGTH bytes.
Return values
true If a valid MAC address was retrieved.
false If the timeout was reached or an error occurred.
Definition at line 512 of file wifi.c.
References WIFI_GetResult(), WIFI_GetSavedMAC(), WIFI_RequestInfo(), WIFI_RESULT_ERROR, and WIFI_RESULT_SUCCESS.