LED_FreeRTOS
Provides the core capabilities for LED FreeRTOS related functions.
Data Structures
struct LED_RTOS_Command
Structure representing a command to be executed by the LED task.
Enumerations
enum LED_Command { LED_CMD_ON
, LED_CMD_OFF
, LED_CMD_TOGGLE
 }
Enumeration representing LED operation types for queued commands.
Functions
bool LED_RTOS_Ready (void)
Checks whether the LED RTOS task and queue have been initialized successfully.
void LED_RTOS_InitRedInt (bool state, LED_ModelType model)
Initializes the internal red LED and creates the LED control task.
void LED_RTOS_InitAllInt (bool state, LED_ModelType model)
Initializes all internal RGB LEDs and creates the LED control task.
void LED_RTOS_InitAllExt (bool state, LED_ModelType model)
Initializes all external RGB LEDs and creates the LED control task.
void LED_RTOS_InitSemaphore (LED_ModelType model)
Initializes the semaphore-style traffic light LED set and creates the LED control task.
bool LED_RTOS_GetState (LED_ColorValueType color, bool *state)
Gets the current state of a specific LED.
void LED_RTOS_On (LED_ColorValueType color, LED_ModelType model)
Turns on the specified LED asynchronously using the LED task.
void LED_RTOS_Off (LED_ColorValueType color, LED_ModelType model)
Turns off the specified LED asynchronously using the LED task.
void LED_RTOS_Toggle (LED_ColorValueType color, LED_ModelType model)
Toggles the state of the specified LED asynchronously using the LED task.
void LED_RTOS_Delete (void)
Shuts down and cleans up the LED RTOS module.
Detailed Description
Provides the core capabilities for LED FreeRTOS related functions.
Enumeration Type Documentation
LED_Command
enum LED_Command
Enumeration representing LED operation types for queued commands.
      This enum defines the possible actions that can be queued
      to control an LED (turn it on, off, or toggle its state).
Enumerator
LED_CMD_ON Command to turn the LED ON.
LED_CMD_OFF Command to turn the LED OFF.
LED_CMD_TOGGLE Command to TOGGLE the LED state.
Definition at line 43 of file led_rtos.h.
Function Documentation
LED_RTOS_Delete()
void LED_RTOS_Delete (void)
Shuts down and cleans up the LED RTOS module.
      Deletes the LED task, queue, and mutex.
Definition at line 147 of file led_rtos.c.
LED_RTOS_GetState()
bool LED_RTOS_GetState (LED_ColorValueType color, bool * state)
Gets the current state of a specific LED.
      This function retrieves the state of the LED corresponding to the given color.
      It uses a mutex to ensure thread-safe access. If the mutex cannot be obtained,
      the function returns false and the state is not updated.
Parameters
color The color of the LED to query.
state Pointer to a boolean variable to store the LED state. Will be set to true if the LED is ON, or false if OFF.
Return values
true If the state was successfully retrieved.
false If the mutex could not be acquired or state retrieval failed.
Definition at line 96 of file led_rtos.c.
References LED_GetState().
LED_RTOS_InitAllExt()
void LED_RTOS_InitAllExt (bool state, LED_ModelType model)
Initializes all external RGB LEDs and creates the LED control task.
Parameters
state Initial state of all LEDs (true = on, false = off).
model LED model type.
Note
This function sets up red, green, and blue external LEDs.
Definition at line 74 of file led_rtos.c.
References LED_Init().
LED_RTOS_InitAllInt()
void LED_RTOS_InitAllInt (bool state, LED_ModelType model)
Initializes all internal RGB LEDs and creates the LED control task.
Parameters
state Initial state of all LEDs (true = on, false = off).
model LED model type.
Note
This function sets up red, green, and blue internal LEDs.
Definition at line 67 of file led_rtos.c.
References LED_Init().
LED_RTOS_InitRedInt()
void LED_RTOS_InitRedInt (bool state, LED_ModelType model)
Initializes the internal red LED and creates the LED control task.
Parameters
state Initial state of the LED (true = on, false = off).
model LED model type.
Note
Should be called during system initialization if only the red internal LED is used.
Definition at line 62 of file led_rtos.c.
References LED_Init().
LED_RTOS_InitSemaphore()
void LED_RTOS_InitSemaphore (LED_ModelType model)
Initializes the semaphore-style traffic light LED set and creates the LED control task.
Parameters
model LED model type.
Note
Initializes red and yellow LEDs to OFF and green to ON by default.
Definition at line 81 of file led_rtos.c.
References LED_Init().
LED_RTOS_Off()
void LED_RTOS_Off (LED_ColorValueType color, LED_ModelType model)
Turns off the specified LED asynchronously using the LED task.
Parameters
color LED color to turn off.
model LED model type.
Definition at line 123 of file led_rtos.c.
References LED_RTOS_Command::color, LED_RTOS_Command::command, LED_CMD_OFF, LED_RTOS_Ready(), and LED_RTOS_Command::model.
LED_RTOS_On()
void LED_RTOS_On (LED_ColorValueType color, LED_ModelType model)
Turns on the specified LED asynchronously using the LED task.
Parameters
color LED color to turn on.
model LED model type.
Definition at line 111 of file led_rtos.c.
References LED_RTOS_Command::color, LED_RTOS_Command::command, LED_CMD_ON, LED_RTOS_Ready(), and LED_RTOS_Command::model.
LED_RTOS_Ready()
bool LED_RTOS_Ready (void)
Checks whether the LED RTOS task and queue have been initialized successfully.
Returns
true if ready; false otherwise.
Definition at line 92 of file led_rtos.c.
Referenced by LED_RTOS_Off(), LED_RTOS_On(), and LED_RTOS_Toggle().
LED_RTOS_Toggle()
void LED_RTOS_Toggle (LED_ColorValueType color, LED_ModelType model)
Toggles the state of the specified LED asynchronously using the LED task.
Parameters
color LED color to toggle.
model LED model type.
Definition at line 135 of file led_rtos.c.
References LED_RTOS_Command::color, LED_RTOS_Command::command, LED_CMD_TOGGLE, LED_RTOS_Ready(), and LED_RTOS_Command::model.