FLASHCONTROL
Provides the core capabilities for flash memory control functions.
Functions
int FLASHCONTROL_EraseSector (unsigned int sector)
Erases the specified flash memory sector.
int FLASHCONTROL_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Writes data from source to the specified flash destination address.
int FLASHCONTROL_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Verifies that the contents of the flash match the source buffer.
char * FLASHCONTROL_GetResultMsg (int resultValue)
Converts a status code into a human-readable message string.
Detailed Description
Provides the core capabilities for flash memory control functions.
Function Documentation
FLASHCONTROL_EraseSector()
int FLASHCONTROL_EraseSector (unsigned int sector)
Erases the specified flash memory sector.
Parameters
sector Flash sector number to erase.
Returns
Status code indicating success or error.
Definition at line 20 of file flashcontrol.c.
References FLASH_EraseSector().
Referenced by FLASH_RTOS_EraseSector().
FLASHCONTROL_GetResultMsg()
char * FLASHCONTROL_GetResultMsg (int resultValue)
Converts a status code into a human-readable message string.
Parameters
resultValue Status code returned by flash operations.
Returns
Pointer to a constant string with the message, or NULL if unknown.
Definition at line 78 of file flashcontrol.c.
FLASHCONTROL_VerifyData()
int FLASHCONTROL_VerifyData (void * dstAddr, void * srcAddr, unsigned int size)
Verifies that the contents of the flash match the source buffer.
   Comparison is word-aligned and may pad the size to the next multiple of 4 bytes.
Parameters
dstAddr Destination flash address.
srcAddr Source buffer address in RAM.
size Number of bytes to compare (up to 4096).
Returns
Status code indicating success or error.
Definition at line 61 of file flashcontrol.c.
References COUNT_ERROR, DST_ADDR_ERROR, FLASH_VerifyData(), and SRC_ADDR_ERROR.
Referenced by FLASH_RTOS_VerifyData().
FLASHCONTROL_WriteData()
int FLASHCONTROL_WriteData (void * dstAddr, void * srcAddr, unsigned int size)
Writes data from source to the specified flash destination address.
   Data is padded to the next valid flash write size (256/512/1024/4096 bytes).
Parameters
dstAddr Destination address in flash memory.
srcAddr Source address in RAM.
size Number of bytes to write (must be <= 4096).
Returns
Status code indicating success or error.
Definition at line 24 of file flashcontrol.c.
References COUNT_ERROR, DST_ADDR_ERROR, and FLASH_WriteData().
Referenced by FLASH_RTOS_WriteData().